-- AlterTable
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "benefitItems" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "timeline" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "howToJoin" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "requirements" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "judgingNote" TEXT;
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "quota" INTEGER;
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "tone" TEXT;
ALTER TABLE "Activity" ADD COLUMN IF NOT EXISTS "rewardSkillCodes" TEXT[] DEFAULT ARRAY[]::TEXT[];
